# Generated by Django 5.0.6 on 2026-04-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_teacher",
            field=models.BooleanField(
                default=False,
                help_text="Может создавать публичные колоды и управлять пользователями",
            ),
        ),
    ]
