# Generated by Django 5.0.6 on 2026-04-27 06:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("description", models.TextField(blank=True, default="")),
                (
                    "visibility",
                    models.CharField(
                        choices=[("private", "Приватная"), ("public", "Публичная")],
                        db_index=True,
                        default="private",
                        max_length=10,
                    ),
                ),
                ("is_public", models.BooleanField(db_index=True, default=False)),
                ("target_language", models.CharField(default="en", max_length=50)),
                ("native_language", models.CharField(default="ru", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="liked_decks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Лайки",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="decks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Колода",
                "verbose_name_plural": "Колоды",
                "db_table": "decks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DeckProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cards_mastered", models.PositiveIntegerField(default=0)),
                ("cards_learning", models.PositiveIntegerField(default=0)),
                ("cards_struggling", models.PositiveIntegerField(default=0)),
                ("last_session_at", models.DateTimeField(blank=True, null=True)),
                ("total_time_spent_seconds", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="cards.deck",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deck_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс по колоде",
                "verbose_name_plural": "Прогресс по колодам",
                "db_table": "deck_progress",
            },
        ),
        migrations.CreateModel(
            name="Flashcard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("term", models.CharField(db_index=True, max_length=255)),
                ("definition", models.TextField()),
                (
                    "part_of_speech",
                    models.CharField(blank=True, default="", max_length=50),
                ),
                ("example_sentence", models.TextField(blank=True, default="")),
                (
                    "base_difficulty",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "Very Easy"),
                            (2, "Easy"),
                            (3, "Medium"),
                            (4, "Hard"),
                            (5, "Very Hard"),
                        ],
                        default=3,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("image_prompt", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "deck",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flashcard_set",
                        to="cards.deck",
                    ),
                ),
            ],
            options={
                "verbose_name": "Флеш-карта",
                "verbose_name_plural": "Флеш-карты",
                "db_table": "flashcards",
                "ordering": ["term"],
            },
        ),
        migrations.CreateModel(
            name="AIGenerationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_prompt", models.TextField()),
                ("response_content", models.TextField(blank=True, default="")),
                ("model_used", models.CharField(default="gpt-4o-mini", max_length=100)),
                ("tokens_used", models.PositiveIntegerField(default=0)),
                ("latency_ms", models.PositiveIntegerField(default=0)),
                ("was_successful", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ai_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "flashcard",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="generation_logs",
                        to="cards.flashcard",
                    ),
                ),
            ],
            options={
                "verbose_name": "Лог ИИ-генерации",
                "verbose_name_plural": "Логи ИИ-генерации",
                "db_table": "ai_generation_logs",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserCardProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("repetition_number", models.PositiveSmallIntegerField(default=1)),
                (
                    "easiness_factor",
                    models.FloatField(
                        default=2.5,
                        validators=[
                            django.core.validators.MinValueValidator(1.3),
                            django.core.validators.MaxValueValidator(2.5),
                        ],
                    ),
                ),
                ("inter_repetition_interval", models.PositiveIntegerField(default=0)),
                ("consecutive_correct", models.PositiveSmallIntegerField(default=0)),
                ("total_attempts", models.PositiveIntegerField(default=0)),
                ("total_errors", models.PositiveIntegerField(default=0)),
                ("average_response_time_ms", models.PositiveIntegerField(default=0)),
                ("last_reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "next_review_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("last_quality_response", models.PositiveSmallIntegerField(default=0)),
                ("requires_context_refresh", models.BooleanField(default=False)),
                (
                    "flashcard",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="cards.flashcard",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Прогресс по карточке",
                "verbose_name_plural": "Прогресс по карточкам",
                "db_table": "user_card_progress",
            },
        ),
        migrations.AddIndex(
            model_name="deck",
            index=models.Index(
                fields=["owner", "created_at"], name="decks_owner_i_49e91c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deckprogress",
            index=models.Index(
                fields=["user", "updated_at"], name="deck_progre_user_id_48c583_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="deckprogress",
            unique_together={("user", "deck")},
        ),
        migrations.AddIndex(
            model_name="flashcard",
            index=models.Index(
                fields=["deck", "is_active"], name="flashcards_deck_id_8a1561_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="flashcard",
            index=models.Index(
                fields=["term", "deck"], name="flashcards_term_998a48_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercardprogress",
            index=models.Index(
                fields=["user", "next_review_at"], name="user_card_p_user_id_b68bb0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usercardprogress",
            index=models.Index(
                fields=["user", "requires_context_refresh"],
                name="user_card_p_user_id_0928d5_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usercardprogress",
            unique_together={("user", "flashcard")},
        ),
    ]
