# Generated by Django 5.0.6 on 2026-04-22 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="is_public",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Публичная колода видна всем пользователям",
            ),
        ),
    ]
