# Generated by Django 5.0.6 on 2026-04-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cards", "0002_deck_is_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="deck",
            name="visibility",
            field=models.CharField(
                choices=[("private", "Приватная"), ("public", "Публичная")],
                db_index=True,
                default="private",
                help_text="Кто может видеть эту колоду",
                max_length=10,
            ),
        ),
    ]
